{
 "title": "Docker UCP Dashboard",
 "description": "Docker EE UCP 3.1 Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cpu",
    "query": "query_result(topk(10, max_over_time(ucp_engine_container_cpu_percent{manager='false'}[${__range_s}s])))"
   },
   {
    "name": "mem",
    "query": "query_result(topk(10, max_over_time(ucp_engine_container_memory_usage_bytes{manager='false'}[${__range_s}s])))"
   }
  ]
 },
 "panels": [
  {
   "title": "Unhealthy Manager Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ucp_engine_container_unhealth{manager='true'})"
    }
   ]
  },
  {
   "title": "Unhealthy Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ucp_engine_node_health == 0)"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "count(ucp_engine_node_health)" }
   ]
  },
  {
   "title": "Total Manager Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ucp_engine_num_cpu_cores{manager='true'})"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "count(ucp_engine_pod_ready)" }
   ]
  },
  {
   "title": "Unhealthy Nodes",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "count(ucp_engine_node_health == 0) by (nodeName)"
    }
   ]
  },
  {
   "title": "Unhealthy Containers",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "(sum(ucp_engine_container_unhealth) by (name) ==1)+0"
    }
   ]
  },
  {
   "title": "Total Node Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ucp_engine_num_cpu_cores{manager='false'})"
    }
   ]
  },
  {
   "title": "Total Manager Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ucp_engine_container_health{manager='true'})"
    }
   ]
  },
  {
   "title": "Unhealthy Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ucp_engine_container_unhealth{manager='false'})"
    }
   ]
  },
  {
   "title": "Total Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ucp_engine_container_health)"
    }
   ]
  },
  {
   "title": "Total non Manager Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ucp_engine_container_health{manager='false'})"
    }
   ]
  },
  {
   "title": "Total Pod Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ucp_engine_pod_container_ready)"
    }
   ]
  },
  {
   "title": "Pod Containers Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ucp_engine_pod_container_ready == 0)"
    }
   ]
  },
  {
   "title": "UCP Master CPU %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(ucp_engine_container_cpu_percent{manager='true'}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "UCP Master Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(ucp_engine_container_memory_usage_bytes{manager='true'}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers/Images/Volumes per Server",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 7 },
   "targets": [
    { "expr": "(ucp_engine_containers)+0" },
    { "expr": "(ucp_engine_images)+0" },
    { "expr": "(ucp_engine_volumes)+0" }
   ]
  },
  {
   "title": "Top 10 Containers by CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ucp_engine_container_cpu_percent{container=~\"$cpu\"}",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "Top 10 Containers by Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ucp_engine_container_memory_usage_bytes{container=~\"$mem\"}",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "Top 10 Containers by Memory %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10, ucp_engine_container_memory_usage_percent)",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  }
 ]
}